#!/bin/bash

##### INSTALAÇÃO DO GRAFANA 

echo "aguarde enquanto ocorre a instalação do GRAFANA"

# Adicionando o repositório

echo "[grafana]
name=grafana
baseurl=https://packages.grafana.com/oss/rpm
repo_gpgcheck=1
enabled=1
gpgcheck=1
gpgkey=https://packages.grafana.com/gpg.key
sslverify=1
sslcacert=/etc/pki/tls/certs/ca-bundle.crt" | sudo tee /etc/yum.repos.d/grafana.repo


echo "repositório criado"

#Instalando o Grafana

sudo dnf install grafana -y

echo "instalação do grafana concluído"

# Habilitando o serviço do grafana

sudo systemctl enable --now grafana-server
sudo systemctl status grafana-server

echo "serviço do grafana habilitado"

# Configrando o Firewall para acessar o grafana

sudo netstat -pnltu
sudo firewall-cmd --add-port=3000/tcp --permanent
sudo firewall-cmd --reload


# parte do script para mostrar o link do zabbix
# Execute o comando 'ip a' e filtra o endereço IP da interface enp0s3
ip_address=$(ip a | awk '/enp0s3/ && /inet / {gsub(/\/.*/, "", $2); print $2}')

# Exiba o endereço para acessar o zabbix
echo "para poder acessar o Grafana acessa com o http:/"$ip_address":3000"
echo "Login: admin" 
echo "Senha: admin"
echo "Após conectar com a senha provisória, você verá a opção de alterar a senha em seguida."

